export const RECORD_LANGUAGES = [
    /* {value: 'en-US', label: 'English (United States)'},
    {value: 'en-AU', label: 'English (Australia)'},
    {value: 'en-CA', label: 'English (Canada)'},
    {value: 'en-GH', label: 'English (Ghana)'},
    {value: 'en-GB', label: 'English (United Kingdom)'},
    {value: 'en-IN', label: 'English (India)'},
    {value: 'en-IE', label: 'English (Ireland)'},
    {value: 'en-KE', label: 'English (Kenya)'},
    {value: 'en-NZ', label: 'English (New Zealand)'},
    {value: 'en-NG', label: 'English (Nigeria)'},
    {value: 'en-PH', label: 'English (Philippines)'},
    {value: 'en-SG', label: 'English (Singapore)'},
    {value: 'en-ZA', label: 'English (South Africa)'},
    {value: 'en-TZ', label: 'English (Tanzania)'}, */

    {value: 'af-ZA', label: 'Afrikaans (South Africa)'},
    {value: 'am-ET', label: 'Amharic (Ethiopia)'},
    {value: 'hy-AM', label: 'Armenian (Armenia)'},
    {value: 'az-AZ', label: 'Azerbaijani (Azerbaijan)'},
    {value: 'id-ID', label: 'Indonesian (Indonesia)'},
    {value: 'ms-MY', label: 'Malay (Malaysia)'},
    {value: 'bn-BD', label: 'Bengali (Bangladesh)'},
    {value: 'bn-IN', label: 'Bengali (India)'},
    {value: 'ca-ES', label: 'Catalan (Spain)'},
    {value: 'cs-CZ', label: 'Czech (Czech Republic)'},
    {value: 'da-DK', label: 'Danish (Denmark)'},
    {value: 'de-DE', label: 'German (Germany)'},
    {value: 'es-AR', label: 'Spanish (Argentina)'},
    {value: 'es-BO', label: 'Spanish (Bolivia)'},
    {value: 'es-CL', label: 'Spanish (Chile)'},
    {value: 'es-CO', label: 'Spanish (Colombia)'},
    {value: 'es-CR', label: 'Spanish (Costa Rica)'},
    {value: 'es-EC', label: 'Spanish (Ecuador)'},
    {value: 'es-SV', label: 'Spanish (El Salvador)'},
    {value: 'es-ES', label: 'Spanish (Spain)'},
    {value: 'es-US', label: 'Spanish (United States)'},
    {value: 'es-GT', label: 'Spanish (Guatemala)'},
    {value: 'es-HN', label: 'Spanish (Honduras)'},
    {value: 'es-MX', label: 'Spanish (Mexico)'},
    {value: 'es-NI', label: 'Spanish (Nicaragua)'},
    {value: 'es-PA', label: 'Spanish (Panama)'},
    {value: 'es-PY', label: 'Spanish (Paraguay)'},
    {value: 'es-PE', label: 'Spanish (Peru)'},
    {value: 'es-PR', label: 'Spanish (Puerto Rico)'},
    {value: 'es-DO', label: 'Spanish (Dominican Republic)'},
    {value: 'es-UY', label: 'Spanish (Uruguay)'},
    {value: 'es-VE', label: 'Spanish (Venezuela)'},

    {value: 'eu-ES', label: 'Basque (Spain)'},
    {value: 'fil-PH', label: 'Filipino (Philippines)'},

    {value: 'fr-CA', label: 'French (Canada)'},
    {value: 'fr-FR', label: 'French (France)'},

    {value: 'gl-ES', label: 'Galician (Spain)'},
    {value: 'ka-GE', label: 'Georgian (Georgia)'},
    {value: 'gu-IN', label: 'Gujarati (India)'},
    {value: 'hr-HR', label: 'Croatian (Croatia)'},
    {value: 'zu-ZA', label: 'Zulu (South Africa)'},
    {value: 'is-IS', label: 'Icelandic (Iceland)'},
    {value: 'it-IT', label: 'Italian (Italy)'},
    {value: 'jv-ID', label: 'Javanese (Indonesia)'},
    {value: 'kn-IN', label: 'Kannada (India)'},
    {value: 'km-KH', label: 'Khmer (Cambodia)'},
    {value: 'lo-LA', label: 'Lao (Laos)'},
    {value: 'lv-LV', label: 'Latvian (Latvia)'},
    {value: 'lt-LT', label: 'Lithuanian (Lithuania)'},
    {value: 'hu-HU', label: 'Hungarian (Hungary)'},
    {value: 'ml-IN', label: 'Malayalam (India)'},
    {value: 'mr-IN', label: 'Marathi (India)'},
    {value: 'nl-NL', label: 'Dutch (Netherlands)'},
    {value: 'ne-NP', label: 'Nepali (Nepal)'},
    {value: 'nb-NO', label: 'Norwegian Bokmål (Norway)'},
    {value: 'pl-PL', label: 'Polish (Poland)'},

    {value: 'pt-BR', label: 'Portuguese (Brazil)'},
    {value: 'pt-PT', label: 'Portuguese (Portugal)'},

    {value: 'ro-RO', label: 'Romanian (Romania)'},
    {value: 'si-LK', label: 'Sinhala (Sri Lanka)'},
    {value: 'sk-SK', label: 'Slovak (Slovakia)'},
    {value: 'sl-SI', label: 'Slovenian (Slovenia)'},
    {value: 'su-ID', label: 'Sundanese (Indonesia)'},

    {value: 'sw-TZ', label: 'Swahili (Tanzania)'},
    {value: 'sw-KE', label: 'Swahili (Kenya)'},

    {value: 'fi-FI', label: 'Finnish (Finland)'},
    {value: 'sv-SE', label: 'Swedish (Sweden)'},

    {value: 'ta-IN', label: 'Tamil (India)'},
    {value: 'ta-SG', label: 'Tamil (Singapore)'},
    {value: 'ta-LK', label: 'Tamil (Sri Lanka)'},
    {value: 'ta-MY', label: 'Tamil (Malaysia)'},

    {value: 'te-IN', label: 'Telugu (India)'},
    {value: 'vi-VN', label: 'Vietnamese (Vietnam)'},
    {value: 'tr-TR', label: 'Turkish (Turkey)'},

    {value: 'ur-PK', label: 'Urdu (Pakistan)'},
    {value: 'ur-IN', label: 'Urdu (India)'},
    
    {value: 'el-GR', label: 'Greek (Greece)'},
    {value: 'bg-BG', label: 'Bulgarian (Bulgaria)'},
    {value: 'ru-RU', label: 'Russian (Russia)'},
    {value: 'sr-RS', label: 'Serbian (Serbia)'},
    {value: 'uk-UA', label: 'Ukrainian (Ukraine)'},
    {value: 'he-IL', label: 'Hebrew (Israel)'},

    {value: 'ar-IL', label: 'Arabic (Israel)'},
    {value: 'ar-JO', label: 'Arabic (Jordan)'},
    {value: 'ar-AE', label: 'Arabic (United Arab Emirates)'},
    {value: 'ar-BH', label: 'Arabic (Bahrain)'},
    {value: 'ar-DZ', label: 'Arabic (Algeria)'},
    {value: 'ar-SA', label: 'Arabic (Saudi Arabia)'},
    {value: 'ar-IQ', label: 'Arabic (Iraq)'},
    {value: 'ar-KW', label: 'Arabic (Kuwait)'},
    {value: 'ar-MA', label: 'Arabic (Morocco)'},
    {value: 'ar-TN', label: 'Arabic (Tunisia)'},
    {value: 'ar-OM', label: 'Arabic (Oman)'},
    {value: 'ar-PS', label: 'Arabic (Palestine)'},
    {value: 'ar-QA', label: 'Arabic (Qatar)'},
    {value: 'ar-LB', label: 'Arabic (Lebanon)'},
    {value: 'ar-EG', label: 'Arabic (Egypt)'},

    {value: 'fa-IR', label: 'Persian (Iran)'},
    {value: 'hi-IN', label: 'Hindi (India)'},
    {value: 'th-TH', label: 'Thai (Thailand)'},
    {value: 'ko-KR', label: 'Korean (South Korea)'},
    {value: 'ja-JP', label: 'Japanese (Japan)'},

    {value: 'zh-TW', label: 'Chinese, Mandarin (Traditional, Taiwan)'},
    {value: 'yue-Hant-HK', label: 'Chinese, Cantonese (Traditional, Hong Kong)'},
    {value: 'zh-HK', label: 'Chinese, Mandarin (Simplified, Hong Kong)'},
    {value: 'zh', label: 'Chinese, Mandarin (Simplified, China)'}

]